// app/layout.tsx

import type { Metadata } from "next";
import { Inter,Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'

// Load the Inter font with Latin subset
const inter = Outfit({ subsets: ["latin"] });

// Metadata for the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      
        <html lang="en">
          <body className={inter.className}>
            {children}
          </body>
        </html>
      
    </ClerkProvider>
  );
}
